// types/rapportActivite.ts
export interface RapportActivite {
  id_rapport: number;
  id_permis: number;
  date_remise_reelle: string;
  etat_activite: string;
  leve_topo_3112: string | null;
  leve_topo_3006: string | null;
  plan_exploitation: string | null;
  date_debut_travaux: string | null;
  vente_exportation: string | null;
  importation: string | null;
  valeur_equipement_acquis: number | null;
  pros_expl_entamee: string | null;
  avancee_travaux: string | null;
  travaux_realises: string | null;
  nbr_ouvrages: number | null;
  volume: number | null;
  resume_activites: string | null;
  investissements_realises: number | null;
  qte_explosifs: number | null;
  qte_explosifs_DIM: number | null;
  detonateurs: number | null;
  dmr: number | null;
  cordeau_detonant: number | null;
  meche_lente: number | null;
  relais: number | null;
  DEI: number | null;
  effectif_cadre: number | null;
  effectif_maitrise: number | null;
  effectif_execution: number | null;
  production_toutvenant: number | null;
  production_marchande: number | null;
  production_vendue: number | null;
  production_stocke: number | null;
  stock_T_V: number | null;
  stock_produit_marchand: number | null;
  production_sable: number | null;
  poussieres: number | null;
  rejets_laverie: number | null;
  fumee_gaz: number | null;
  autres_effluents: number | null;
  nbr_accidents: number | null;
  accidents_mortels: number | null;
  accidents_non_mortels: number | null;
  nbrs_jours_perdues: number | null;
  taux_frequence: number | null;
  taux_gravite: number | null;
  nbrs_incidents: number | null;
  nbrs_malades_pro: number | null;
  remise_etat_realisee: string | null;
  cout_remise_etat: number | null;
  commentaires_generaux: string | null;
  rapport_url: string | null;
}